import type { Meta, StoryObj } from "@storybook/react";
import React from "react";
import { ComprehensivePlanDocument } from "../components/ComprehensivePlanDocument";
import { CELL_CYPHER_ONE, TRUST_TIMELINE, NIST_POSTURE_BASELINE } from "../data/demo-fixtures";
import type { SignalsUiEnvelope } from "../types/signals-ui-envelope";

const meta: Meta<typeof ComprehensivePlanDocument> = {
  title: "Signal Components/12 — Plan Document",
  component: ComprehensivePlanDocument,
  tags: ["autodocs"],
};
export default meta;
type Story = StoryObj<typeof ComprehensivePlanDocument>;

export const QuantumReadinessPlan: Story = {
  args: {
    title: "Post-Quantum Cryptography Readiness Plan",
    subtitle: "Prairie Fuels Inc. — CER-Designated Operator — Generated by CYPHER ONE",
    sections: [
      {
        title: "Executive Summary",
        defaultOpen: true,
        content: (
          <div className="space-y-3 text-sm text-text-secondary">
            <p>CBOM analysis identified 337 cryptographic usage points across Prairie Fuels IT and SCADA/OT systems (Honeywell Experion DCS, Allen-Bradley ControlLogix, Schneider SAGE 3030, Cisco ASA). Of these, 8 entries (57% of critical assets) use algorithms vulnerable to quantum attack. ControlLogix PLCs and SAGE 3030 RTUs use RSA-1024 with zero crypto-agility — immediate replacement required.</p>
            <p>Bill C-8 §9(1)(e) anticipated regulations mandate PQC migration roadmaps for designated operators. This plan provides a phased migration strategy prioritized by HNDL exposure and operational risk.</p>
          </div>
        ),
      },
      {
        title: "Phase 1: Immediate Actions (Q3 2026)",
        content: (
          <div className="space-y-2 text-sm text-text-secondary">
            <p className="font-medium text-accent-blue">Complete within 90 days</p>
            <ul className="list-disc pl-5 space-y-1">
              <li>Retire RSA-1024 on ControlLogix 5580 and SAGE 3030 firmware signing (critical risk 0.96/0.94)</li>
              <li>Deploy ML-KEM + X25519 hybrid on Host-01 Cisco ASA 5545-X VPN TLS termination</li>
              <li>Complete Honeywell/AB/Schneider OT protocol fingerprinting for remaining 11 targets</li>
              <li>Request CBOM attestations from Honeywell, Rockwell, Schneider firmware suppliers</li>
            </ul>
          </div>
        ),
      },
      {
        title: "Phase 2: Foundation (Q4 2026 – Q2 2027)",
        content: (
          <p className="text-sm text-text-secondary">
            Crypto-agility architecture patterns for pipeline SCADA. Hybrid PKI migration. Continuous CBOM monitoring via one-shadow cell. First PQC tabletop exercise with OT team.
          </p>
        ),
      },
      {
        title: "Phase 3: Migration (Q3 2027 – Q4 2028)",
        content: (
          <p className="text-sm text-text-secondary">
            Systematic migration of all PQC-vulnerable algorithms, sequenced by CBOM risk score. SCADA systems with zero crypto-agility require firmware replacement — vendor coordination critical.
          </p>
        ),
      },
      {
        title: "Phase 4: Validation & Ongoing (2029+)",
        content: (
          <p className="text-sm text-text-secondary">
            Continuous CBOM monitoring. Annual PQC readiness assessment aligned with Bill C-8 reporting. Satellite-linked RTU audit completion. Board-level crypto posture reporting.
          </p>
        ),
      },
      {
        title: "Budget Framework",
        content: (
          <div className="text-sm text-text-secondary">
            <p>Phase 1: $180K–$280K | Phase 2: $450K–$700K | Phase 3: $1.2M–$1.8M (firmware replacement) | Phase 4: $120K–$200K/year</p>
          </div>
        ),
      },
    ],
  },
};

export const WithEnvelope: Story = {
  args: {
    ...QuantumReadinessPlan.args,
    envelope: {
      hsmlState: "HSML_ACTIVE",
      confidence: TRUST_TIMELINE[0],
      emittingCell: CELL_CYPHER_ONE,
      nistPosture: NIST_POSTURE_BASELINE[4],
      said: "E_DEMO_SAID_ENVELOPE",
    } satisfies SignalsUiEnvelope,
  },
};
