import type { Meta, StoryObj } from "@storybook/react";
import React from "react";
import { BillC8MandateCard } from "../components/BillC8MandateCard";
import { CBOMDiscoveryDashboard } from "../components/CBOMDiscoveryDashboard";
import { CBOMExecutiveDashboard } from "../components/CBOMExecutiveDashboard";
import { QuantumInterlockCard } from "../components/QuantumInterlockCard";
import { ComprehensivePlanDocument } from "../components/ComprehensivePlanDocument";
import { TimelineView } from "../components/TimelineView";
import { PriorityList } from "../components/PriorityList";
import {
  PQC_MILESTONES,
  PQC_PRIORITIES,
  CBOM_DISCOVERY_METHODS,
  CBOM_SCAN_FAILURES,
  CBOM_ENTRIES,
  CBOM_COVERAGE_GAPS,
  QUANTUM_ACTION_ITEMS,
} from "../data/demo-fixtures";

const meta: Meta = {
  title: "Walkthroughs/02 — UC2 Quantum",
};
export default meta;

// ---------------------------------------------------------------------------
// ACT VI — 08:30 AM — Quantum Governance
// ---------------------------------------------------------------------------

export const ActVI_BillC8Mandate: StoryObj = {
  name: "08:30 — Bill C-8 Mandate",
  render: () => (
    <div className="max-w-2xl">
      <p className="text-[10px] tracking-telemetry text-text-data uppercase mb-4">Act VI — Bill C-8 quantum mandate surfaces • one-intel</p>
      <BillC8MandateCard />
    </div>
  ),
};

export const ActVI_PQCTimeline: StoryObj = {
  name: "08:31 — PQC Timeline",
  render: () => (
    <div className="max-w-3xl">
      <p className="text-[10px] tracking-telemetry text-text-data uppercase mb-4">Act VI — Quantum transition timeline with regulatory gates</p>
      <TimelineView milestones={PQC_MILESTONES} currentDate="2026-06" />
    </div>
  ),
};

export const ActVI_Priorities: StoryObj = {
  name: "08:32 — Quantum Priorities",
  render: () => (
    <div className="max-w-3xl">
      <p className="text-[10px] tracking-telemetry text-text-data uppercase mb-4">Act VI — Top 3 immediate priorities from one-shadow assessment</p>
      <PriorityList priorities={PQC_PRIORITIES} />
    </div>
  ),
};

export const ActVI_CBOMDiscovery: StoryObj = {
  name: "08:33 — CBOM Discovery",
  render: () => (
    <div className="max-w-4xl">
      <p className="text-[10px] tracking-telemetry text-text-data uppercase mb-4">Act VI — one-shadow CBOM scan in progress • pipeline SCADA/OT + IT</p>
      <CBOMDiscoveryDashboard
        methods={CBOM_DISCOVERY_METHODS}
        totalInventoryCount={337}
        coveragePercent={72}
        failures={CBOM_SCAN_FAILURES}
      />
    </div>
  ),
};

export const ActVI_CBOMExecutive: StoryObj = {
  name: "08:35 — CBOM Executive Summary",
  render: () => (
    <div className="max-w-4xl">
      <p className="text-[10px] tracking-telemetry text-text-data uppercase mb-4">Act VI — CycloneDX 1.6 CBOM inventory analysis • PQC vulnerability map</p>
      <CBOMExecutiveDashboard
        entries={CBOM_ENTRIES}
        gaps={CBOM_COVERAGE_GAPS}
        failures={CBOM_SCAN_FAILURES}
        actionItems={QUANTUM_ACTION_ITEMS}
      />
    </div>
  ),
};

export const ActVI_QuantumInterlock: StoryObj = {
  name: "08:38 — Quantum Interlock",
  render: () => (
    <div className="max-w-2xl">
      <p className="text-[10px] tracking-telemetry text-text-data uppercase mb-4">Act VI — FIPS-203/204 enforcement interlock • one-vector</p>
      <QuantumInterlockCard />
    </div>
  ),
};

export const ActVI_ComprehensivePlan: StoryObj = {
  name: "08:40 — Quantum Readiness Plan",
  render: () => (
    <div className="max-w-4xl">
      <p className="text-[10px] tracking-telemetry text-text-data uppercase mb-4">Act VI — Full PQC migration plan for CER-regulated pipeline operator</p>
      <ComprehensivePlanDocument
        title="Post-Quantum Cryptography Readiness Plan"
        subtitle="Prairie Fuels Inc. — CER-Designated Operator — Generated by CYPHER ONE"
        sections={[
          {
            title: "Executive Summary",
            defaultOpen: true,
            content: (
              <p className="text-sm text-text-secondary">
                CBOM analysis identified 337 cryptographic usage points across Prairie Fuels IT and SCADA/OT systems
                (Honeywell Experion DCS, Allen-Bradley ControlLogix, Schneider SAGE 3030, Cisco ASA).
                Of these, 8 entries (57% of critical assets) use algorithms vulnerable to quantum attack.
                ControlLogix PLCs and SAGE 3030 RTUs use RSA-1024 with zero crypto-agility — immediate replacement required.
                Bill C-8 §9(1)(e) anticipated regulations mandate PQC migration roadmaps for designated operators.
              </p>
            ),
          },
          {
            title: "Phase 1: Immediate Actions (Q3 2026)",
            content: (
              <ul className="text-sm text-text-secondary list-disc pl-5 space-y-1">
                <li>Retire RSA-1024 on ControlLogix 5580 and SAGE 3030 firmware signing (critical risk 0.96/0.94)</li>
                <li>Deploy ML-KEM + X25519 hybrid on Host-01 Cisco ASA 5545-X VPN TLS termination</li>
                <li>Complete SCADA/OT protocol fingerprinting for 11 remaining targets</li>
                <li>Request CBOM attestations from 6 vendor firmware suppliers</li>
              </ul>
            ),
          },
          {
            title: "Phase 2: Foundation (Q4 2026 – Q2 2027)",
            content: (
              <p className="text-sm text-text-secondary">
                Crypto-agility architecture patterns for pipeline SCADA. Hybrid PKI migration.
                Continuous CBOM monitoring via one-shadow cell. First PQC tabletop with OT team.
              </p>
            ),
          },
          {
            title: "Phase 3: Migration (Q3 2027 – Q4 2028)",
            content: (
              <p className="text-sm text-text-secondary">
                Systematic migration of all PQC-vulnerable algorithms, sequenced by CBOM risk score.
                SCADA systems with zero crypto-agility require firmware replacement — vendor coordination critical.
              </p>
            ),
          },
          {
            title: "Phase 4: Validation & Ongoing (2029+)",
            content: (
              <p className="text-sm text-text-secondary">
                Continuous CBOM monitoring. Annual PQC readiness assessment aligned with Bill C-8 reporting.
                Satellite-linked RTU audit completion. Board-level crypto posture reporting.
              </p>
            ),
          },
          {
            title: "Budget Framework",
            content: (
              <div className="text-sm text-text-secondary">
                <p>Phase 1: $180K–$280K | Phase 2: $450K–$700K | Phase 3: $1.2M–$1.8M (firmware replacement driven) | Phase 4: $120K–$200K/year</p>
              </div>
            ),
          },
        ]}
      />
    </div>
  ),
};
