import React, { useState, useCallback } from "react";
import type { SignalsUiEnvelope } from "../types/signals-ui-envelope";
import { HeaderStatus, HsmlStateOverlay } from "./primitives";

function ChevronIcon({ open }: { open: boolean }) {
  return (
    <svg
      width="14"
      height="14"
      viewBox="0 0 16 16"
      fill="none"
      className={`transition-transform duration-300 ${open ? "rotate-90" : "rotate-0"}`}
    >
      <path
        d="M6 4l4 4-4 4"
        stroke="currentColor"
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}

interface PlanSection {
  title: string;
  content: React.ReactNode;
  defaultOpen?: boolean;
}

function CollapsibleSection({ section }: { section: PlanSection }) {
  const [open, setOpen] = useState(section.defaultOpen ?? false);
  const toggle = useCallback(() => setOpen((o) => !o), []);

  return (
    <div className="border-b border-border-subtle last:border-b-0">
      <button
        type="button"
        onClick={toggle}
        className="w-full flex items-center gap-3 px-5 py-4 text-left cursor-pointer group hover:bg-[rgba(0,102,255,0.03)] transition-colors"
      >
        <span className="text-text-muted group-hover:text-accent-blue transition-colors">
          <ChevronIcon open={open} />
        </span>
        <span className="eyebrow">// {section.title.toUpperCase()}</span>
      </button>
      {open && (
        <div className="px-5 pb-5 pt-0 ml-[1.75rem] text-sm text-text-secondary font-light leading-relaxed animate-[fadeIn_150ms_ease-out]">
          {section.content}
        </div>
      )}
    </div>
  );
}

export interface ComprehensivePlanDocumentProps {
  title: string;
  subtitle?: string;
  sections: PlanSection[];
  envelope?: SignalsUiEnvelope;
}

export function ComprehensivePlanDocument({
  title,
  subtitle,
  sections,
  envelope,
}: ComprehensivePlanDocumentProps) {
  const now = new Date();
  const timestamp = now.toISOString().replace("T", " ").slice(0, 19) + " UTC";

  return (
    <div className="relative">
      {envelope && <HsmlStateOverlay hsmlState={envelope.hsmlState} />}
    <div className="glass-panel border-l-2 border-l-accent-blue rounded-none overflow-hidden">
      <div
        className="radial-glow"
        style={{ width: 400, height: 200, top: -60, left: -80, background: "radial-gradient(circle, rgba(0,102,255,0.10) 0%, rgba(0,0,0,0) 70%)" }}
      />

      {/* Header */}
      <div className="px-5 pt-5 pb-4 border-b border-border-subtle relative z-10">
        <div className="flex items-center justify-between mb-4">
          <div className="flex items-center gap-2.5">
            <div className="w-2 h-2 flex-shrink-0 rounded-full bg-accent-blue" />
            <span className="text-[11px] font-medium uppercase tracking-label text-text-secondary">
              DOCUMENT
            </span>
          </div>
          <HeaderStatus envelope={envelope} />
        </div>
        <h3 className="font-extralight text-2xl text-white leading-tight text-glow-sm">{title}</h3>
        {subtitle && (
          <p className="mt-1.5 text-xs font-light text-text-muted uppercase tracking-telemetry">{subtitle}</p>
        )}
      </div>

      {/* Sections */}
      <div className="relative z-10">
        {sections.map((s, i) => (
          <CollapsibleSection key={i} section={s} />
        ))}
      </div>

      {/* Footer */}
      <div className="px-5 py-4 border-t border-border-subtle flex items-center justify-between relative z-10">
        <span className="telemetry">GENERATED BY CYPHER ONE // {timestamp}</span>
        <div className="flex items-center gap-2">
        </div>
        <span className="text-[10px] uppercase tracking-telemetry text-text-muted">
          G1 SIGNALS LAB // CONFIDENTIAL
        </span>
      </div>
    </div>
    </div>
  );
}

export default ComprehensivePlanDocument;
